# http://www.appveyor.com/docs/appveyor-yml
# testo
# environment:
#   matrix:
#   - TARGET: x86_64-pc-windows-msvc
#     BITS: 64
#     MSYS2: 1
#   - TARGET: i686-pc-windows-msvc
#     BITS: 32
#     MSYS2: 1

# build: off

install:
#  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
#  - rustup-init.exe -y --default-host %TARGET%
#  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
#  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - bash -version
#  - rustc -V
#  - cargo -V

before_build:
- del "MMManaged\\Dn5-MMManaged.fsproj" # this confuses paket restore, so remove it
- installdeps.bat nopause
#- dir packages

build_script: build.bat AppveyorBuild nopause

test_script: build.bat AppveyorTest nopause

after_test: build.bat AppveyorPackage nopause

artifacts:
  - path: deploy/*.zip
