# http://www.appveyor.com/docs/appveyor-yml

before_build: 
- installdeps.bat nopause
#- dir packages

build_script: build.bat AppveyorBuild nopause

test_script: build.bat AppveyorTest nopause

after_test: build.bat AppveyorPackage nopause

artifacts:
  - path: deploy/*.zip
